const MARKERS_LIST = {
    LOAD_REQUESTED: 'MARKERS_LIST.LOAD_REQUESTED',
    LOAD_FAILED: 'MARKERS_LIST.LOAD_FAILED',
    LIST_RECEIVED: 'MARKERS_LIST.LIST_RECEIVED'
}

const MARKERS_REMOVE = {
    REMVOE_REQUESTED: 'MARKERS_REMOVE.REMVOE_REQUESTED',
    REMOVE_FAILED: 'MARKERS_REMOVE.REMOVE_FAILED',
    REMOVE_SUCCEEDED: 'MARKERS_REMOVE.REMOVE_SUCCEEDED'
}

export default {
    MARKERS_LIST,
    MARKERS_REMOVE
}